class PublicPages {
	HOME = '/'
	LOGIN = '/login'
	REGISTER = '/register'
	PLANS = '/wishes'
	ROOMCREATE = '/createroom'
	EQUIPMENTCREATE = '/equipmentcreate'
	PARSER = '/parser'
	EDUCATOR = '/educators'
	BUILDINGS = '/buildings'
	POSITIONS = '/positions'
	DEPARTMENTS = '/departments'
	TEACHERS = '/teachers'
	AUDIENCETYPES = '/audiencetypes'
	USERS = '/users'
	GROUPS = '/groups'
	PROFILE = '/profile'
	CONSTRUCTOR = '/constructor'
	SETPAIRSTOTEACHER = '/setpairs'
	MERGEDISCIPLINES = '/merge-disciplines'
	BUSYRESOURCE = '/busy-resource'
	ZAOCONSTRUCTOR = '/zao-constructor'
}

export const PUBLIC_PAGES = new PublicPages()
